name: Nick Chambon Music
favicon: null
layout_spectrum: 0.8459284955170006
typography_spectrum: 0.01618861686438322
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6f1f4'
    - '#000002'
    - '#004a00'
    - '#008500'
    - '#99b2b9'
  brandStrength: 0.375
  lightness: 0.25
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
