name: Nick Chambon Music
favicon: null
layout_spectrum: 0.8459284955170006
typography_spectrum: 0.01618861686438322
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f7f8'
    - '#00243e'
    - '#7ba9ce'
    - '#487d9d'
    - '#c1d9e7'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
